# Note: This configuration is specifically for LLNL compute
# clusters. To run testing locally, consult the README in the ci_test
# directory.

stages:
  - run-all-clusters

# run-catalyst-testing:
#   stage: run-all-clusters
#   trigger:
#     strategy: depend
#     include: .gitlab/catalyst/pipeline.yml

# run-corona-testing:
#   stage: run-all-clusters
#   trigger:
#     strategy: depend
#     include: .gitlab/corona/pipeline.yml

# run-lassen-testing:
#   stage: run-all-clusters
#   trigger:
#     strategy: depend
#     include: .gitlab/lassen/pipeline.yml

run-pascal-testing:
  stage: run-all-clusters
  trigger:
    strategy: depend
    include: .gitlab/pascal/pipeline.yml

# run-ray-testing:
#   stage: run-all-clusters
#   trigger:
#     strategy: depend
#     include: .gitlab/ray/pipeline.yml
