variables:
  CUSTOM_CI_BUILDS_DIR: "/usr/workspace/vanessen/mygitlab-runner-builds-dir"
  CI_DEBUG_TRACE: "true"
  
before_script:
  - echo "=== before_script section ==="

after_script:
  - echo "=== after_script section ==="

stages:
  - compiler
  - integration
  - unit

compilerRay:
  stage: compiler
  tags:
    - ray
    - shell
  script:
    - echo "=== compilerRay section ==="
#    - .gitlab/scripts/build.sh

integrationRay:
  stage: compiler
  tags:
    - ray
    - shell
  script:
    - echo "=== integrationRay section ==="

unitRay:
  stage: compiler
  tags:
    - ray
    - shell
  script:
    - echo "=== unitRay section ==="
    - echo "FINISHED"
