################################################################################
## Copyright (c) 2014-2024, Lawrence Livermore National Security, LLC.
## Produced at the Lawrence Livermore National Laboratory.
## Written by the LBANN Research Team (B. Van Essen, et al.) listed in
## the CONTRIBUTORS file. <lbann-dev@llnl.gov>
##
## LLNL-CODE-697807.
## All rights reserved.
##
## This file is part of LBANN: Livermore Big Artificial Neural Network
## Toolkit. For details, see http://software.llnl.gov/LBANN or
## https://github.com/LLNL/LBANN.
##
## Licensed under the Apache License, Version 2.0 (the "Licensee"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at:
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
## implied. See the License for the specific language governing
## permissions and limitations under the license.
################################################################################

default:
  id_tokens:
     SITE_ID_TOKEN:
        aud: https://lc.llnl.gov/gitlab

stages:
  - build

include:
  local: "/.gitlab/build-and-test-common.yml"

clang-14-0-6-cuda-11-8-0-pascal:
  variables:
    COMPILER_FAMILY: clang
    MODULES: "clang/14.0.6-magic openmpi/4.1.2 cuda/11.8.0 ninja/1.11.1"
    WITH_HALF: "1"
    WITH_FFT: "1"
  extends: [.build-and-test-on-pascal, .build-and-test]

clang-14-0-6-cuda-11-8-0-distconv-pascal:
  variables:
    COMPILER_FAMILY: clang
    MODULES: "clang/14.0.6-magic openmpi/4.1.2 cuda/11.8.0 ninja/1.11.1"
    WITH_HALF: "1"
    WITH_FFT: "1"
    WITH_DISTCONV: "1"
  extends: [.build-and-test-on-pascal, .build-and-test]

.build-and-test-on-pascal:
  stage: build
  tags: [pascal, batch]
