################################################################################
## Copyright (c) 2014-2023, Lawrence Livermore National Security, LLC.
## Produced at the Lawrence Livermore National Laboratory.
## Written by the LBANN Research Team (B. Van Essen, et al.) listed in
## the CONTRIBUTORS file. <lbann-dev@llnl.gov>
##
## LLNL-CODE-697807.
## All rights reserved.
##
## This file is part of LBANN: Livermore Big Artificial Neural Network
## Toolkit. For details, see http://software.llnl.gov/LBANN or
## https://github.com/LLNL/LBANN.
##
## Licensed under the Apache License, Version 2.0 (the "Licensee"); you
## may not use this file except in compliance with the License.  You may
## obtain a copy of the License at:
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
## implied. See the License for the specific language governing
## permissions and limitations under the license.
################################################################################

# This is the testing pipeline for the Corona cluster at LLNL. This
# cluster builds the LBANN applications and libraries using a single
# compiler toolchain and then runs a collection of tests. Testing
# output is in JUnit format and parsed by the pipeline for web
# viewing.

# See the Catalyst pipeline for more thorough documentation.

include:
  - .gitlab/common/common.yml

stages:
  - allocate
  - build
  - test
  - deallocate

# Get LC resources.
allocate lc resources:
  stage: allocate
  extends:
    - .tioga common
    - .lbann-base-vars
  variables:
    GIT_STRATEGY: none
  script:
    - echo "== ACQUIRING FLUX RESOURCES =="
    - echo "${WITH_WEEKLY:+Running with --weekly}"
    - export TEST_TIME=$([[ -n "${WITH_WEEKLY}" ]] && echo "150m" || echo "120m")
    - export LBANN_NNODES=$([[ -n "${WITH_WEEKLY}" ]] && echo "4" || echo "2")
    - export FLUX_F58_FORCE_ASCII=t
    - export JOB_ID="UNALLOCATED"
#    - timeout 30s jobid=$(flux --parent alloc -N ${LBANN_NNODES} --exclusive -t ${TEST_TIME} --job-name=${JOB_NAME} --bg)
    - jobid=$(flux --parent alloc -N ${LBANN_NNODES} --exclusive -t ${TEST_TIME} --job-name=${JOB_NAME} --bg)
    - export JOB_ID=$jobid
  timeout: 2m
#  timeout: 6h
  allow_failure: true

# Build LBANN and establish the Spack environment for this pipeline.
build and install:
  extends:
    - .tioga common
    - .lbann-base-vars
    - .lbann-artifacts
  stage: build
  script:
    # - !reference [.check_allocation, script]
    - echo "== BUILDING LBANN =="
    - export FLUX_F58_FORCE_ASCII=t
    - "export JOB_ID=$(flux jobs -no {id}:{name} | grep ${JOB_NAME} | awk -F: '{print $1}')"
    - "export LBANN_NNODES=$(flux jobs -no {id}:{name}:{nnodes} | grep ${JOB_NAME} | awk -F: '{print $3}')"
    - !reference [.setup_spack, script]
    - flux proxy ${JOB_ID} flux run -N 1 -t 30m ./scripts/build_lbann.sh --ci ${SPACK_DEPS_FLAG}
      -l ${SPACK_ENV_NAME} -j ${BUILD_TASKS} ${CLEAN_BUILD_FLAG}
      -p py-pip --ci-pip --
      +deterministic +vision +numpy +unit_tests ${SPACK_SPECS}
    - export TEST_TASKS_PER_NODE=4
    - export TEST_MPIBIND_FLAG="--mpibind=off"
    - export SPACK_ARCH=$(flux proxy ${JOB_ID} flux run -N 1 spack arch)
    - export SPACK_ARCH_TARGET=$(flux proxy ${JOB_ID} flux run -N 1 spack arch -t)
    - export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}
    - export LD_LIBRARY_PATH=${ROCM_PATH}/lib:${LD_LIBRARY_PATH}
    - !reference [.setup_lbann, script]
    - flux proxy ${JOB_ID} .gitlab/common/run-catch-tests-flux.sh
  allow_failure:
    exit_codes:
      - 42

# Run the Python-based unit tests.
unit tests:
  extends:
    - .tioga common
    - .lbann-base-vars
    - .uses spack environment
  stage: test
  dependencies:
    - build and install
  script:
    # - !reference [.check_allocation, script]
    - echo "== RUNNING PYTHON-BASED UNIT TESTS =="
    - echo "Testing $(which lbann)"
    - export FLUX_F58_FORCE_ASCII=t
    - export OMP_NUM_THREADS=10
    - "export FLUX_JOB_ID=$(flux jobs -no {id}:{name} | grep ${JOB_NAME} | awk -F: '{print $1}')"
    - cd ci_test/unit_tests
    - export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}
    - flux proxy ${FLUX_JOB_ID} lbann_pfe.sh -m pytest -s -vv --durations=0 --junitxml=results.xml ${TEST_FLAG}
  artifacts:
    when: always
    paths:
      - ci_test/unit_tests/results.xml
    reports:
      junit: ci_test/unit_tests/results.xml
  allow_failure:
    exit_codes:
      - 42

# Run the Python-based integration tests.
integration tests:
  extends:
    - .tioga common
    - .lbann-base-vars
    - .uses spack environment
  stage: test
  dependencies:
    - build and install
  rules:
    - !reference [.lbann-test-rules, rules]
  script:
    # - !reference [.check_allocation, script]
    - echo "== RUNNING PYTHON-BASED INTEGRATION TESTS =="
    - echo "Testing $(which lbann)"
    - export FLUX_F58_FORCE_ASCII=t
    - export OMP_NUM_THREADS=10
    - "export FLUX_JOB_ID=$(flux jobs -no {id}:{name} | grep ${JOB_NAME} | awk -F: '{print $1}')"
    - cd ci_test/integration_tests
    - export WEEKLY_FLAG=${WITH_WEEKLY:+--weekly}
    - export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}
    - flux proxy ${FLUX_JOB_ID} lbann_pfe.sh -m pytest -s -vv --durations=0 ${WEEKLY_FLAG} --junitxml=results.xml ${TEST_FLAG}
  artifacts:
    when: always
    paths:
      - ci_test/integration_tests/results.xml
    reports:
      junit: ci_test/integration_tests/results.xml
  allow_failure:
    exit_codes:
      - 42

# This is a dummy job that checks the Catch2 testing.
check catch2 tests:
  variables:
    GIT_STRATEGY: none
  extends:
    - .tioga common
    - .lbann-base-vars
  stage: test
  dependencies:
    - build and install
  script:
    - !reference [.check_allocation, script]
    - ([[ $(find ${RESULTS_DIR} -name "catch-tests-failed.txt" | wc -l) -eq 0 ]])
  artifacts:
    reports:
      junit: ${RESULTS_DIR}/*.xml
  allow_failure:
    exit_codes:
      - 42

# Cleanup the pipeline's Spack environment.
remove spack environment:
  extends:
    - .tioga common
    - .lbann-base-vars
    - .cleanup old spack environment
  stage: deallocate
  variables:
    GIT_STRATEGY: none
  when: always
  allow_failure: true

# Free the allocation we obtained in "allocate lc resources".
release allocation:
  stage: deallocate
  extends:
    - .tioga common
    - .lbann-base-vars
  variables:
    GIT_STRATEGY: none
  when: always
  script:
    - echo "== RELEASING RESOURCES =="
    - "export JOB_ID=$(flux jobs -no {id}:{name} | grep ${JOB_NAME} | awk -F: '{print $1}')"
    - ([[ -n "${JOB_ID}" ]] && flux job cancel ${JOB_ID})
  allow_failure: true

# Variables for Tioga.
.tioga common:
  variables:
    # Just the obvious identifier. Which specific node doesn't matter.
    SYSTEM_NAME: tioga
    # SPACK_USER_CACHE_PATH: /g/g14/lbannusr/spack_repos/.spack_${SYSTEM_NAME}
    # SPACK_REPO: spack_repos/spack_${SYSTEM_NAME}.git
    SPACK_USER_CACHE_PATH: /g/g14/lbannusr/spack_repos/.spack_test
    SPACK_REPO: spack_repos/spack_test.git

    # These are system-specific specs that should be forwarded to the
    # build script
    SPACK_SPECS: "+rocm"

  tags:
    - tioga
    - shell
